# Generated by Django 4.2.20 on 2025-05-17 11:25

from django.db import migrations, models
import layouts.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('faq_title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('faq_description', models.TextField()),
                ('faq_type', models.CharField(blank=True, default='global', max_length=55, null=True)),
                ('issued_by', models.CharField(blank=True, default='Super Admin', max_length=25, null=True)),
                ('language', models.CharField(blank=True, default='en', max_length=10, null=True)),
                ('translated_languages', models.JSONField(blank=True, default=layouts.models.default_translated_languages, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TermsAndConditions',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('type', models.CharField(blank=True, default='global', max_length=55, null=True)),
                ('issued_by', models.CharField(blank=True, default='Super Admin', max_length=25, null=True)),
                ('is_approved', models.BooleanField(default=True)),
                ('language', models.CharField(blank=True, default='en', max_length=10, null=True)),
                ('translated_languages', models.JSONField(blank=True, default=layouts.models.default_translated_languages, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
