# Generated by Django 4.2.20 on 2025-05-17 11:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('tracking_number', models.CharField(max_length=50, unique=True)),
                ('customer_id', models.IntegerField()),
                ('customer_contact', models.CharField(max_length=20)),
                ('customer_name', models.CharField(blank=True, max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sales_tax', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('note', models.TextField(blank=True, null=True)),
                ('cancelled_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cancelled_tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cancelled_delivery_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('language', models.CharField(default='en', max_length=10)),
                ('coupon_id', models.IntegerField(blank=True, null=True)),
                ('parent_id', models.IntegerField(blank=True, null=True)),
                ('shop_id', models.IntegerField(blank=True, null=True)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('payment_gateway', models.CharField(choices=[('CASH', 'Cash'), ('CASH_ON_DELIVERY', 'Cash on Delivery'), ('CREDIT_CARD', 'Credit Card'), ('PAYPAL', 'PayPal'), ('BANK_TRANSFER', 'Bank Transfer'), ('OTHER', 'Other')], default='CASH_ON_DELIVERY', max_length=50)),
                ('altered_payment_gateway', models.CharField(blank=True, max_length=50, null=True)),
                ('logistics_provider', models.CharField(blank=True, max_length=255, null=True)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('delivery_time', models.CharField(blank=True, max_length=255, null=True)),
                ('order_status', models.CharField(choices=[('order-pending', 'Order Pending'), ('order-processing', 'Order Processing'), ('order-completed', 'Order Completed'), ('order-cancelled', 'Order Cancelled')], default='order-pending', max_length=50)),
                ('payment_status', models.CharField(choices=[('payment-pending', 'Payment Pending'), ('payment-completed', 'Payment Completed'), ('payment-failed', 'Payment Failed')], default='payment-pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wallet_point', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('batch_number', models.CharField(blank=True, max_length=50, null=True)),
                ('item_name', models.CharField(blank=True, max_length=200, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('percentage_discount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('sale_price_discount_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('percentage_discount_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('flat_discount_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('total_discount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('quantity', models.IntegerField(blank=True, default=1)),
                ('return_quantity', models.IntegerField(default=0)),
                ('item_value', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('item_total', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
